# Generated by Django 3.0.6 on 2020-06-03 09:11

import acms.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='second_line',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='ease_of_transprtation',
        ),
        migrations.RemoveField(
            model_name='store',
            name='location',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_phone_verified',
        ),
        migrations.AddField(
            model_name='store',
            name='avg_breadth',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='avg_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storetimings',
            name='open_day',
            field=models.CharField(choices=[(acms.models.DayChoice['Monday'], 'Monday'), (acms.models.DayChoice['Tuesday'], 'Tuesday'), (acms.models.DayChoice['Wednesday'], 'Wednesday'), (acms.models.DayChoice['Thursday'], 'Thursday'), (acms.models.DayChoice['Friday'], 'Friday'), (acms.models.DayChoice['Saturday'], 'Saturday'), (acms.models.DayChoice['Sunday'], 'Sunday')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
