# Generated by Django 3.0.6 on 2020-06-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acms', '0002_auto_20200603_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='name',
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
